[phases.setup]
nixPkgs = ["python39", "nodejs-18_x", "python39Packages.pip"]

[phases.install]
cmds = [
  "npm install --prefix frontend",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend",
  "python3 backend/manage.py collectstatic --noinput"
]

[start]
cmd = "python3 -m gunicorn dashboard_project.wsgi --bind 0.0.0.0:$PORT --chdir backend"
